name = "MTKCardiacCellModels"
uuid = "cf70e313-3958-40e5-b5fe-3d717db61409"
authors = ["jClugstor <jadonclugston@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
